package com.example.widgetlingo

import android.content.Context
import androidx.room.Database
import androidx.room.Room
import androidx.room.RoomDatabase
import androidx.room.migration.Migration
import androidx.sqlite.db.SupportSQLiteDatabase
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.launch

@Database(entities = [WordEntity::class], version = 1, exportSchema = false)
abstract class AppDatabase : RoomDatabase() {
    abstract fun wordDao(): WordDao

    companion object {
        @Volatile
        private var INSTANCE: AppDatabase? = null

        fun getDatabase(context: Context): AppDatabase {
            return INSTANCE ?: synchronized(this) {
                val instance = Room.databaseBuilder(
                    context.applicationContext,
                    AppDatabase::class.java,
                    "word_database"
                ).addCallback(WordDatabaseCallback())
                    .addMigrations(MIGRATION_1_2) // Подготовка миграции для будущих версий
                    .build()
                INSTANCE = instance
                instance
            }
        }

        // Миграция с версии 1 на 2 (пример, если версия изменится)
        val MIGRATION_1_2 = object : Migration(1, 2) {
            override fun migrate(database: SupportSQLiteDatabase) {
                // Добавьте изменения БД здесь, если нужно
            }
        }

        private class WordDatabaseCallback : Callback() {
            override fun onCreate(db: SupportSQLiteDatabase) {
                super.onCreate(db)
                INSTANCE?.let { database ->
                    CoroutineScope(Dispatchers.IO).launch {
                        populateDatabase(database.wordDao())
                    }
                }
            }

            suspend fun populateDatabase(wordDao: WordDao) {
                // Расширенные тестовые слова для разных языков и сложностей
                // Добавлено: По 70 слов на каждый язык и сложность (всего много новых хороших слов)
                wordDao.insertAll(listOf(
                    // Английский - Beginner (70 слов)
                    WordEntity(word = "hello", translation = "привет", transcription = "[hɛˈloʊ]", language = "english", difficulty = "beginner"),
                    WordEntity(word = "world", translation = "мир", transcription = "[wɜrld]", language = "english", difficulty = "beginner"),
                    WordEntity(word = "apple", translation = "яблоко", transcription = "[ˈæpəl]", language = "english", difficulty = "beginner"),
                    WordEntity(word = "book", translation = "книга", transcription = "[bʊk]", language = "english", difficulty = "beginner"),
                    WordEntity(word = "cat", translation = "кошка", transcription = "[kæt]", language = "english", difficulty = "beginner"),
                    WordEntity(word = "dog", translation = "собака", transcription = "[dɔɡ]", language = "english", difficulty = "beginner"),
                    WordEntity(word = "house", translation = "дом", transcription = "[haʊs]", language = "english", difficulty = "beginner"),
                    WordEntity(word = "tree", translation = "дерево", transcription = "[tri]", language = "english", difficulty = "beginner"),
                    WordEntity(word = "car", translation = "машина", transcription = "[kɑr]", language = "english", difficulty = "beginner"),
                    WordEntity(word = "sun", translation = "солнце", transcription = "[sʌn]", language = "english", difficulty = "beginner"),
                    WordEntity(word = "moon", translation = "луна", transcription = "[mun]", language = "english", difficulty = "beginner"),
                    WordEntity(word = "water", translation = "вода", transcription = "[ˈwɔtər]", language = "english", difficulty = "beginner"),
                    WordEntity(word = "food", translation = "еда", transcription = "[fud]", language = "english", difficulty = "beginner"),
                    WordEntity(word = "friend", translation = "друг", transcription = "[frɛnd]", language = "english", difficulty = "beginner"),
                    WordEntity(word = "family", translation = "семья", transcription = "[ˈfæməli]", language = "english", difficulty = "beginner"),
                    WordEntity(word = "school", translation = "школа", transcription = "[skul]", language = "english", difficulty = "beginner"),
                    WordEntity(word = "teacher", translation = "учитель", transcription = "[ˈtitʃər]", language = "english", difficulty = "beginner"),
                    WordEntity(word = "student", translation = "ученик", transcription = "[ˈstudnt]", language = "english", difficulty = "beginner"),
                    WordEntity(word = "pen", translation = "ручка", transcription = "[pɛn]", language = "english", difficulty = "beginner"),
                    WordEntity(word = "paper", translation = "бумага", transcription = "[ˈpeɪpər]", language = "english", difficulty = "beginner"),
                    WordEntity(word = "number", translation = "число", transcription = "[ˈnʌmbər]", language = "english", difficulty = "beginner"),
                    WordEntity(word = "color", translation = "цвет", transcription = "[ˈkʌlər]", language = "english", difficulty = "beginner"),
                    WordEntity(word = "red", translation = "красный", transcription = "[rɛd]", language = "english", difficulty = "beginner"),
                    WordEntity(word = "blue", translation = "синий", transcription = "[bluː]", language = "english", difficulty = "beginner"),
                    WordEntity(word = "green", translation = "зелёный", transcription = "[ɡriːn]", language = "english", difficulty = "beginner"),
                    WordEntity(word = "one", translation = "один", transcription = "[wʌn]", language = "english", difficulty = "beginner"),
                    WordEntity(word = "two", translation = "два", transcription = "[tuː]", language = "english", difficulty = "beginner"),
                    WordEntity(word = "three", translation = "три", transcription = "[θriː]", language = "english", difficulty = "beginner"),
                    WordEntity(word = "mother", translation = "мать", transcription = "[ˈmʌðər]", language = "english", difficulty = "beginner"),
                    WordEntity(word = "father", translation = "отец", transcription = "[ˈfɑːðər]", language = "english", difficulty = "beginner"),
                    WordEntity(word = "brother", translation = "брат", transcription = "[ˈbrʌðər]", language = "english", difficulty = "beginner"),
                    WordEntity(word = "sister", translation = "сестра", transcription = "[ˈsɪstər]", language = "english", difficulty = "beginner"),
                    WordEntity(word = "bird", translation = "птица", transcription = "[bɜːrd]", language = "english", difficulty = "beginner"),
                    WordEntity(word = "fish", translation = "рыба", transcription = "[fɪʃ]", language = "english", difficulty = "beginner"),
                    WordEntity(word = "bread", translation = "хлеб", transcription = "[brɛd]", language = "english", difficulty = "beginner"),
                    WordEntity(word = "milk", translation = "молоко", transcription = "[mɪlk]", language = "english", difficulty = "beginner"),
                    WordEntity(word = "cheese", translation = "сыр", transcription = "[tʃiːz]", language = "english", difficulty = "beginner"),
                    WordEntity(word = "coffee", translation = "кофе", transcription = "[ˈkɒfi]", language = "english", difficulty = "beginner"),
                    WordEntity(word = "tea", translation = "чай", transcription = "[tiː]", language = "english", difficulty = "beginner"),
                    WordEntity(word = "city", translation = "город", transcription = "[ˈsɪti]", language = "english", difficulty = "beginner"),
                    WordEntity(word = "country", translation = "страна", transcription = "[ˈkʌntri]", language = "english", difficulty = "beginner"),
                    WordEntity(word = "river", translation = "река", transcription = "[ˈrɪvər]", language = "english", difficulty = "beginner"),
                    WordEntity(word = "mountain", translation = "гора", transcription = "[ˈmaʊntɪn]", language = "english", difficulty = "beginner"),
                    WordEntity(word = "flower", translation = "цветок", transcription = "[ˈflaʊər]", language = "english", difficulty = "beginner"),
                    WordEntity(word = "rain", translation = "дождь", transcription = "[reɪn]", language = "english", difficulty = "beginner"),
                    WordEntity(word = "snow", translation = "снег", transcription = "[snəʊ]", language = "english", difficulty = "beginner"),
                    WordEntity(word = "wind", translation = "ветер", transcription = "[wɪnd]", language = "english", difficulty = "beginner"),
                    WordEntity(word = "happy", translation = "счастливый", transcription = "[ˈhæpi]", language = "english", difficulty = "beginner"),
                    WordEntity(word = "sad", translation = "грустный", transcription = "[sæd]", language = "english", difficulty = "beginner"),
                    WordEntity(word = "big", translation = "большой", transcription = "[bɪɡ]", language = "english", difficulty = "beginner"),
                    WordEntity(word = "small", translation = "маленький", transcription = "[smɔːl]", language = "english", difficulty = "beginner"),
                    WordEntity(word = "good", translation = "хороший", transcription = "[ɡʊd]", language = "english", difficulty = "beginner"),
                    WordEntity(word = "bad", translation = "плохой", transcription = "[bæd]", language = "english", difficulty = "beginner"),
                    WordEntity(word = "hot", translation = "горячий", transcription = "[hɒt]", language = "english", difficulty = "beginner"),
                    WordEntity(word = "cold", translation = "холодный", transcription = "[kəʊld]", language = "english", difficulty = "beginner"),
                    WordEntity(word = "new", translation = "новый", transcription = "[njuː]", language = "english", difficulty = "beginner"),
                    WordEntity(word = "old", translation = "старый", transcription = "[əʊld]", language = "english", difficulty = "beginner"),
                    WordEntity(word = "day", translation = "день", transcription = "[deɪ]", language = "english", difficulty = "beginner"),
                    WordEntity(word = "night", translation = "ночь", transcription = "[naɪt]", language = "english", difficulty = "beginner"),
                    WordEntity(word = "time", translation = "время", transcription = "[taɪm]", language = "english", difficulty = "beginner"),
                    WordEntity(word = "year", translation = "год", transcription = "[jɪər]", language = "english", difficulty = "beginner"),
                    WordEntity(word = "month", translation = "месяц", transcription = "[mʌnθ]", language = "english", difficulty = "beginner"),
                    WordEntity(word = "week", translation = "неделя", transcription = "[wiːk]", language = "english", difficulty = "beginner"),
                    WordEntity(word = "hour", translation = "час", transcription = "[aʊər]", language = "english", difficulty = "beginner"),
                    WordEntity(word = "minute", translation = "минута", transcription = "[ˈmɪnɪt]", language = "english", difficulty = "beginner"),
                    WordEntity(word = "now", translation = "сейчас", transcription = "[naʊ]", language = "english", difficulty = "beginner"),
                    WordEntity(word = "then", translation = "тогда", transcription = "[ðɛn]", language = "english", difficulty = "beginner"),
                    WordEntity(word = "here", translation = "здесь", transcription = "[hɪər]", language = "english", difficulty = "beginner"),
                    WordEntity(word = "there", translation = "там", transcription = "[ðɛər]", language = "english", difficulty = "beginner"),
                    WordEntity(word = "yes", translation = "да", transcription = "[jɛs]", language = "english", difficulty = "beginner"),
                    WordEntity(word = "no", translation = "нет", transcription = "[nəʊ]", language = "english", difficulty = "beginner"),

                    // Английский - Intermediate (70 слов)
                    WordEntity(word = "computer", translation = "компьютер", transcription = "[kəmˈpjutər]", language = "english", difficulty = "intermediate"),
                    WordEntity(word = "data", translation = "данные", transcription = "[ˈdeɪtə]", language = "english", difficulty = "intermediate"),
                    WordEntity(word = "internet", translation = "интернет", transcription = "[ˈɪntərˌnɛt]", language = "english", difficulty = "intermediate"),
                    WordEntity(word = "software", translation = "программное обеспечение", transcription = "[ˈsɔftˌwɛr]", language = "english", difficulty = "intermediate"),
                    WordEntity(word = "hardware", translation = "аппаратное обеспечение", transcription = "[ˈhɑrdˌwɛr]", language = "english", difficulty = "intermediate"),
                    WordEntity(word = "network", translation = "сеть", transcription = "[ˈnɛtˌwɜrk]", language = "english", difficulty = "intermediate"),
                    WordEntity(word = "database", translation = "база данных", transcription = "[ˈdeɪtəˌbeɪs]", language = "english", difficulty = "intermediate"),
                    WordEntity(word = "server", translation = "сервер", transcription = "[ˈsɜrvər]", language = "english", difficulty = "intermediate"),
                    WordEntity(word = "client", translation = "клиент", transcription = "[ˈklaɪənt]", language = "english", difficulty = "intermediate"),
                    WordEntity(word = "protocol", translation = "протокол", transcription = "[ˈproʊtəˌkɔl]", language = "english", difficulty = "intermediate"),
                    WordEntity(word = "browser", translation = "браузер", transcription = "[ˈbraʊzər]", language = "english", difficulty = "intermediate"),
                    WordEntity(word = "application", translation = "приложение", transcription = "[ˌæplɪˈkeɪʃən]", language = "english", difficulty = "intermediate"),
                    WordEntity(word = "file", translation = "файл", transcription = "[faɪl]", language = "english", difficulty = "intermediate"),
                    WordEntity(word = "folder", translation = "папка", transcription = "[ˈfoʊldər]", language = "english", difficulty = "intermediate"),
                    WordEntity(word = "download", translation = "скачать", transcription = "[ˈdaʊnˌloʊd]", language = "english", difficulty = "intermediate"),
                    WordEntity(word = "upload", translation = "загрузить", transcription = "[ˈʌpˌloʊd]", language = "english", difficulty = "intermediate"),
                    WordEntity(word = "email", translation = "электронная почта", transcription = "[ˈiˌmeɪl]", language = "english", difficulty = "intermediate"),
                    WordEntity(word = "password", translation = "пароль", transcription = "[ˈpæsˌwɜrd]", language = "english", difficulty = "intermediate"),
                    WordEntity(word = "username", translation = "имя пользователя", transcription = "[ˈjuzərˌneɪm]", language = "english", difficulty = "intermediate"),
                    WordEntity(word = "security", translation = "безопасность", transcription = "[sɪˈkjʊrɪti]", language = "english", difficulty = "intermediate"),
                    WordEntity(word = "office", translation = "офис", transcription = "[ˈɒfɪs]", language = "english", difficulty = "intermediate"),
                    WordEntity(word = "meeting", translation = "встреча", transcription = "[ˈmiːtɪŋ]", language = "english", difficulty = "intermediate"),
                    WordEntity(word = "project", translation = "проект", transcription = "[ˈprɒdʒɛkt]", language = "english", difficulty = "intermediate"),
                    WordEntity(word = "team", translation = "команда", transcription = "[tiːm]", language = "english", difficulty = "intermediate"),
                    WordEntity(word = "work", translation = "работа", transcription = "[wɜːk]", language = "english", difficulty = "intermediate"),
                    WordEntity(word = "job", translation = "работа", transcription = "[dʒɒb]", language = "english", difficulty = "intermediate"),
                    WordEntity(word = "boss", translation = "босс", transcription = "[bɒs]", language = "english", difficulty = "intermediate"),
                    WordEntity(word = "colleague", translation = "коллега", transcription = "[ˈkɒliːɡ]", language = "english", difficulty = "intermediate"),
                    WordEntity(word = "salary", translation = "зарплата", transcription = "[ˈsæləri]", language = "english", difficulty = "intermediate"),
                    WordEntity(word = "vacation", translation = "отпуск", transcription = "[vəˈkeɪʃən]", language = "english", difficulty = "intermediate"),
                    WordEntity(word = "travel", translation = "путешествие", transcription = "[ˈtrævəl]", language = "english", difficulty = "intermediate"),
                    WordEntity(word = "hotel", translation = "отель", transcription = "[həʊˈtɛl]", language = "english", difficulty = "intermediate"),
                    WordEntity(word = "restaurant", translation = "ресторан", transcription = "[ˈrɛst(ə)rɒnt]", language = "english", difficulty = "intermediate"),
                    WordEntity(word = "menu", translation = "меню", transcription = "[ˈmɛnjuː]", language = "english", difficulty = "intermediate"),
                    WordEntity(word = "order", translation = "заказ", transcription = "[ˈɔːdər]", language = "english", difficulty = "intermediate"),
                    WordEntity(word = "bill", translation = "счёт", transcription = "[bɪl]", language = "english", difficulty = "intermediate"),
                    WordEntity(word = "pay", translation = "платить", transcription = "[peɪ]", language = "english", difficulty = "intermediate"),
                    WordEntity(word = "money", translation = "деньги", transcription = "[ˈmʌni]", language = "english", difficulty = "intermediate"),
                    WordEntity(word = "bank", translation = "банк", transcription = "[bæŋk]", language = "english", difficulty = "intermediate"),
                    WordEntity(word = "card", translation = "карта", transcription = "[kɑːd]", language = "english", difficulty = "intermediate"),
                    WordEntity(word = "phone", translation = "телефон", transcription = "[fəʊn]", language = "english", difficulty = "intermediate"),
                    WordEntity(word = "call", translation = "звонить", transcription = "[kɔːl]", language = "english", difficulty = "intermediate"),
                    WordEntity(word = "message", translation = "сообщение", transcription = "[ˈmɛsɪdʒ]", language = "english", difficulty = "intermediate"),
                    WordEntity(word = "read", translation = "читать", transcription = "[riːd]", language = "english", difficulty = "intermediate"),
                    WordEntity(word = "write", translation = "писать", transcription = "[raɪt]", language = "english", difficulty = "intermediate"),
                    WordEntity(word = "speak", translation = "говорить", transcription = "[spiːk]", language = "english", difficulty = "intermediate"),
                    WordEntity(word = "listen", translation = "слушать", transcription = "[ˈlɪsən]", language = "english", difficulty = "intermediate"),
                    WordEntity(word = "music", translation = "музыка", transcription = "[ˈmjuːzɪk]", language = "english", difficulty = "intermediate"),
                    WordEntity(word = "movie", translation = "фильм", transcription = "[ˈmuːvi]", language = "english", difficulty = "intermediate"),
                    WordEntity(word = "book", translation = "книга", transcription = "[bʊk]", language = "english", difficulty = "intermediate"), // repeat but ok
                    WordEntity(word = "story", translation = "история", transcription = "[ˈstɔːri]", language = "english", difficulty = "intermediate"),
                    WordEntity(word = "news", translation = "новости", transcription = "[njuːz]", language = "english", difficulty = "intermediate"),
                    WordEntity(word = "weather", translation = "погода", transcription = "[ˈwɛðər]", language = "english", difficulty = "intermediate"),
                    WordEntity(word = "rain", translation = "дождь", transcription = "[reɪn]", language = "english", difficulty = "intermediate"),
                    WordEntity(word = "sunny", translation = "солнечный", transcription = "[ˈsʌni]", language = "english", difficulty = "intermediate"),
                    WordEntity(word = "cloudy", translation = "облачный", transcription = "[ˈklaʊdi]", language = "english", difficulty = "intermediate"),
                    WordEntity(word = "sport", translation = "спорт", transcription = "[spɔːrt]", language = "english", difficulty = "intermediate"),
                    WordEntity(word = "football", translation = "футбол", transcription = "[ˈfʊtbɔːl]", language = "english", difficulty = "intermediate"),
                    WordEntity(word = "basketball", translation = "баскетбол", transcription = "[ˈbɑːskɪtˌbɔːl]", language = "english", difficulty = "intermediate"),
                    WordEntity(word = "run", translation = "бегать", transcription = "[rʌn]", language = "english", difficulty = "intermediate"),
                    WordEntity(word = "swim", translation = "плавать", transcription = "[swɪm]", language = "english", difficulty = "intermediate"),
                    WordEntity(word = "health", translation = "здоровье", transcription = "[hɛlθ]", language = "english", difficulty = "intermediate"),
                    WordEntity(word = "doctor", translation = "доктор", transcription = "[ˈdɒktər]", language = "english", difficulty = "intermediate"),
                    WordEntity(word = "hospital", translation = "больница", transcription = "[ˈhɒspɪtl]", language = "english", difficulty = "intermediate"),
                    WordEntity(word = "medicine", translation = "лекарство", transcription = "[ˈmɛdɪsɪn]", language = "english", difficulty = "intermediate"),
                    WordEntity(word = "help", translation = "помощь", transcription = "[hɛlp]", language = "english", difficulty = "intermediate"),
                    WordEntity(word = "problem", translation = "проблема", transcription = "[ˈprɒbləm]", language = "english", difficulty = "intermediate"),
                    WordEntity(word = "solution", translation = "решение", transcription = "[səˈluːʃən]", language = "english", difficulty = "intermediate"),
                    WordEntity(word = "idea", translation = "идея", transcription = "[aɪˈdɪə]", language = "english", difficulty = "intermediate"),
                    WordEntity(word = "plan", translation = "план", transcription = "[plæn]", language = "english", difficulty = "intermediate"),

                    // Английский - Advanced (70 слов)
                    WordEntity(word = "algorithm", translation = "алгоритм", transcription = "[ˈælɡəˌrɪðəm]", language = "english", difficulty = "advanced"),
                    WordEntity(word = "encryption", translation = "шифрование", transcription = "[ɪnˈkrɪpʃən]", language = "english", difficulty = "advanced"),
                    WordEntity(word = "decryption", translation = "расшифровка", transcription = "[diˈkrɪpʃən]", language = "english", difficulty = "advanced"),
                    WordEntity(word = "artificial", translation = "искусственный", transcription = "[ˌɑrtɪˈfɪʃəl]", language = "english", difficulty = "advanced"),
                    WordEntity(word = "intelligence", translation = "интеллект", transcription = "[ɪnˈtɛlɪdʒəns]", language = "english", difficulty = "advanced"),
                    WordEntity(word = "machine", translation = "машина", transcription = "[məˈʃin]", language = "english", difficulty = "advanced"),
                    WordEntity(word = "learning", translation = "обучение", transcription = "[ˈlɜrnɪŋ]", language = "english", difficulty = "advanced"),
                    WordEntity(word = "neural", translation = "нейронный", transcription = "[ˈnʊrəl]", language = "english", difficulty = "advanced"),
                    WordEntity(word = "network", translation = "сеть", transcription = "[ˈnɛtˌwɜrk]", language = "english", difficulty = "advanced"),
                    WordEntity(word = "quantum", translation = "квантовый", transcription = "[ˈkwɑntəm]", language = "english", difficulty = "advanced"),
                    WordEntity(word = "computing", translation = "вычисления", transcription = "[kəmˈpjutɪŋ]", language = "english", difficulty = "advanced"),
                    WordEntity(word = "blockchain", translation = "блокчейн", transcription = "[ˈblɑkˌtʃeɪn]", language = "english", difficulty = "advanced"),
                    WordEntity(word = "cryptocurrency", translation = "криптовалюта", transcription = "[ˌkrɪptoʊˈkɜrənsi]", language = "english", difficulty = "advanced"),
                    WordEntity(word = "virtual", translation = "виртуальный", transcription = "[ˈvɜrtʃuəl]", language = "english", difficulty = "advanced"),
                    WordEntity(word = "reality", translation = "реальность", transcription = "[riˈælɪti]", language = "english", difficulty = "advanced"),
                    WordEntity(word = "augmented", translation = "расширенный", transcription = "[ɔɡˈmɛntɪd]", language = "english", difficulty = "advanced"),
                    WordEntity(word = "cybersecurity", translation = "кибербезопасность", transcription = "[ˈsaɪbər sɪˈkjʊrɪti]", language = "english", difficulty = "advanced"),
                    WordEntity(word = "bigdata", translation = "большие данные", transcription = "[bɪɡ ˈdeɪtə]", language = "english", difficulty = "advanced"),
                    WordEntity(word = "cloud", translation = "облако", transcription = "[klaʊd]", language = "english", difficulty = "advanced"),
                    WordEntity(word = "computing", translation = "вычисления", transcription = "[kəmˈpjutɪŋ]", language = "english", difficulty = "advanced"),
                    WordEntity(word = "philosophy", translation = "философия", transcription = "[fɪˈlɒsəfi]", language = "english", difficulty = "advanced"),
                    WordEntity(word = "economy", translation = "экономика", transcription = "[ɪˈkɒnəmi]", language = "english", difficulty = "advanced"),
                    WordEntity(word = "politics", translation = "политика", transcription = "[ˈpɒlɪtɪks]", language = "english", difficulty = "advanced"),
                    WordEntity(word = "society", translation = "общество", transcription = "[səˈsaɪəti]", language = "english", difficulty = "advanced"),
                    WordEntity(word = "culture", translation = "культура", transcription = "[ˈkʌltʃər]", language = "english", difficulty = "advanced"),
                    WordEntity(word = "history", translation = "история", transcription = "[ˈhɪst(ə)ri]", language = "english", difficulty = "advanced"),
                    WordEntity(word = "science", translation = "наука", transcription = "[ˈsaɪəns]", language = "english", difficulty = "advanced"),
                    WordEntity(word = "technology", translation = "технология", transcription = "[tɛkˈnɒlədʒi]", language = "english", difficulty = "advanced"),
                    WordEntity(word = "environment", translation = "окружающая среда", transcription = "[ɪnˈvaɪrənmənt]", language = "english", difficulty = "advanced"),
                    WordEntity(word = "climate", translation = "климат", transcription = "[ˈklaɪmɪt]", language = "english", difficulty = "advanced"),
                    WordEntity(word = "sustainable", translation = "устойчивый", transcription = "[səˈsteɪnəbəl]", language = "english", difficulty = "advanced"),
                    WordEntity(word = "innovation", translation = "инновация", transcription = "[ˌɪnəʊˈveɪʃən]", language = "english", difficulty = "advanced"),
                    WordEntity(word = "research", translation = "исследование", transcription = "[rɪˈsɜːtʃ]", language = "english", difficulty = "advanced"),
                    WordEntity(word = "theory", translation = "теория", transcription = "[ˈθɪəri]", language = "english", difficulty = "advanced"),
                    WordEntity(word = "hypothesis", translation = "гипотеза", transcription = "[haɪˈpɒθɪsɪs]", language = "english", difficulty = "advanced"),
                    WordEntity(word = "experiment", translation = "эксперимент", transcription = "[ɪkˈspɛrɪmənt]", language = "english", difficulty = "advanced"),
                    WordEntity(word = "analysis", translation = "анализ", transcription = "[əˈnælɪsɪs]", language = "english", difficulty = "advanced"),
                    WordEntity(word = "conclusion", translation = "заключение", transcription = "[kənˈkluːʒən]", language = "english", difficulty = "advanced"),
                    WordEntity(word = "debate", translation = "дебаты", transcription = "[dɪˈbeɪt]", language = "english", difficulty = "advanced"),
                    WordEntity(word = "argument", translation = "аргумент", transcription = "[ˈɑːɡjʊmənt]", language = "english", difficulty = "advanced"),
                    WordEntity(word = "perspective", translation = "перспектива", transcription = "[pəˈspɛktɪv]", language = "english", difficulty = "advanced"),
                    WordEntity(word = "ethics", translation = "этика", transcription = "[ˈɛθɪks]", language = "english", difficulty = "advanced"),
                    WordEntity(word = "morality", translation = "мораль", transcription = "[məˈrælɪti]", language = "english", difficulty = "advanced"),
                    WordEntity(word = "justice", translation = "справедливость", transcription = "[ˈdʒʌstɪs]", language = "english", difficulty = "advanced"),
                    WordEntity(word = "rights", translation = "права", transcription = "[raɪts]", language = "english", difficulty = "advanced"),
                    WordEntity(word = "freedom", translation = "свобода", transcription = "[ˈfriːdəm]", language = "english", difficulty = "advanced"),
                    WordEntity(word = "democracy", translation = "демократия", transcription = "[dɪˈmɒkrəsi]", language = "english", difficulty = "advanced"),
                    WordEntity(word = "capitalism", translation = "капитализм", transcription = "[ˈkæpɪtəlɪzəm]", language = "english", difficulty = "advanced"),
                    WordEntity(word = "socialism", translation = "социализм", transcription = "[ˈsəʊʃəlɪzəm]", language = "english", difficulty = "advanced"),
                    WordEntity(word = "globalization", translation = "глобализация", transcription = "[ˌɡləʊbəlaɪˈzeɪʃən]", language = "english", difficulty = "advanced"),
                    WordEntity(word = "trade", translation = "торговля", transcription = "[treɪd]", language = "english", difficulty = "advanced"),
                    WordEntity(word = "market", translation = "рынок", transcription = "[ˈmɑːkɪt]", language = "english", difficulty = "advanced"),
                    WordEntity(word = "investment", translation = "инвестиция", transcription = "[ɪnˈvɛstmənt]", language = "english", difficulty = "advanced"),
                    WordEntity(word = "profit", translation = "прибыль", transcription = "[ˈprɒfɪt]", language = "english", difficulty = "advanced"),
                    WordEntity(word = "loss", translation = "убыток", transcription = "[lɒs]", language = "english", difficulty = "advanced"),
                    WordEntity(word = "strategy", translation = "стратегия", transcription = "[ˈstrætɪdʒi]", language = "english", difficulty = "advanced"),
                    WordEntity(word = "leadership", translation = "лидерство", transcription = "[ˈliːdərʃɪp]", language = "english", difficulty = "advanced"),
                    WordEntity(word = "management", translation = "управление", transcription = "[ˈmænɪdʒmənt]", language = "english", difficulty = "advanced"),
                    WordEntity(word = "innovation", translation = "инновация", transcription = "[ˌɪnəʊˈveɪʃən]", language = "english", difficulty = "advanced"),
                    WordEntity(word = "creativity", translation = "креативность", transcription = "[ˌkriːeɪˈtɪvɪti]", language = "english", difficulty = "advanced"),
                    WordEntity(word = "psychology", translation = "психология", transcription = "[saɪˈkɒlədʒi]", language = "english", difficulty = "advanced"),
                    WordEntity(word = "behavior", translation = "поведение", transcription = "[bɪˈheɪvjər]", language = "english", difficulty = "advanced"),
                    WordEntity(word = "emotion", translation = "эмоция", transcription = "[ɪˈməʊʃən]", language = "english", difficulty = "advanced"),
                    WordEntity(word = "motivation", translation = "мотивация", transcription = "[ˌməʊtɪˈveɪʃən]", language = "english", difficulty = "advanced"),
                    WordEntity(word = "stress", translation = "стресс", transcription = "[strɛs]", language = "english", difficulty = "advanced"),
                    WordEntity(word = "health", translation = "здоровье", transcription = "[hɛlθ]", language = "english", difficulty = "advanced"),
                    WordEntity(word = "medicine", translation = "медицина", transcription = "[ˈmɛdɪsɪn]", language = "english", difficulty = "advanced"),
                    WordEntity(word = "biology", translation = "биология", transcription = "[baɪˈɒlədʒi]", language = "english", difficulty = "advanced"),
                    WordEntity(word = "physics", translation = "физика", transcription = "[ˈfɪzɪks]", language = "english", difficulty = "advanced"),
                    WordEntity(word = "chemistry", translation = "химия", transcription = "[ˈkɛmɪstri]", language = "english", difficulty = "advanced"),

                    // Русский - Beginner (70 слов)
                    WordEntity(word = "привет", translation = "hello", transcription = "[privet]", language = "russian", difficulty = "beginner"),
                    WordEntity(word = "мир", translation = "world", transcription = "[mir]", language = "russian", difficulty = "beginner"),
                    WordEntity(word = "яблоко", translation = "apple", transcription = "[yabloko]", language = "russian", difficulty = "beginner"),
                    WordEntity(word = "книга", translation = "book", transcription = "[kniga]", language = "russian", difficulty = "beginner"),
                    WordEntity(word = "кошка", translation = "cat", transcription = "[koshka]", language = "russian", difficulty = "beginner"),
                    WordEntity(word = "собака", translation = "dog", transcription = "[sobaka]", language = "russian", difficulty = "beginner"),
                    WordEntity(word = "дом", translation = "house", transcription = "[dom]", language = "russian", difficulty = "beginner"),
                    WordEntity(word = "дерево", translation = "tree", transcription = "[derevo]", language = "russian", difficulty = "beginner"),
                    WordEntity(word = "машина", translation = "car", transcription = "[mashina]", language = "russian", difficulty = "beginner"),
                    WordEntity(word = "солнце", translation = "sun", transcription = "[solntse]", language = "russian", difficulty = "beginner"),
                    WordEntity(word = "луна", translation = "moon", transcription = "[luna]", language = "russian", difficulty = "beginner"),
                    WordEntity(word = "вода", translation = "water", transcription = "[voda]", language = "russian", difficulty = "beginner"),
                    WordEntity(word = "еда", translation = "food", transcription = "[yeda]", language = "russian", difficulty = "beginner"),
                    WordEntity(word = "друг", translation = "friend", transcription = "[drug]", language = "russian", difficulty = "beginner"),
                    WordEntity(word = "семья", translation = "family", transcription = "[sem'ya]", language = "russian", difficulty = "beginner"),
                    WordEntity(word = "школа", translation = "school", transcription = "[shkola]", language = "russian", difficulty = "beginner"),
                    WordEntity(word = "учитель", translation = "teacher", transcription = "[uchitel']", language = "russian", difficulty = "beginner"),
                    WordEntity(word = "ученик", translation = "student", transcription = "[uchenik]", language = "russian", difficulty = "beginner"),
                    WordEntity(word = "ручка", translation = "pen", transcription = "[ruchka]", language = "russian", difficulty = "beginner"),
                    WordEntity(word = "бумага", translation = "paper", transcription = "[bumaga]", language = "russian", difficulty = "beginner"),
                    WordEntity(word = "да", translation = "yes", transcription = "[da]", language = "russian", difficulty = "beginner"),
                    WordEntity(word = "нет", translation = "no", transcription = "[nɛt]", language = "russian", difficulty = "beginner"),
                    WordEntity(word = "пожалуйста", translation = "please", transcription = "[pazhalusta]", language = "russian", difficulty = "beginner"),
                    WordEntity(word = "спасибо", translation = "thank you", transcription = "[spasibo]", language = "russian", difficulty = "beginner"),
                    WordEntity(word = "извините", translation = "sorry", transcription = "[izvinite]", language = "russian", difficulty = "beginner"),
                    WordEntity(word = "мама", translation = "mom", transcription = "[mama]", language = "russian", difficulty = "beginner"),
                    WordEntity(word = "папа", translation = "dad", transcription = "[papa]", language = "russian", difficulty = "beginner"),
                    WordEntity(word = "брат", translation = "brother", transcription = "[brat]", language = "russian", difficulty = "beginner"),
                    WordEntity(word = "сестра", translation = "sister", transcription = "[sestra]", language = "russian", difficulty = "beginner"),
                    WordEntity(word = "ребёнок", translation = "child", transcription = "[rebyonok]", language = "russian", difficulty = "beginner"),
                    WordEntity(word = "один", translation = "one", transcription = "[odin]", language = "russian", difficulty = "beginner"),
                    WordEntity(word = "два", translation = "two", transcription = "[dva]", language = "russian", difficulty = "beginner"),
                    WordEntity(word = "три", translation = "three", transcription = "[tri]", language = "russian", difficulty = "beginner"),
                    WordEntity(word = "красный", translation = "red", transcription = "[krasnyy]", language = "russian", difficulty = "beginner"),
                    WordEntity(word = "синий", translation = "blue", transcription = "[siniy]", language = "russian", difficulty = "beginner"),
                    WordEntity(word = "зелёный", translation = "green", transcription = "[zelenyy]", language = "russian", difficulty = "beginner"),
                    WordEntity(word = "птица", translation = "bird", transcription = "[ptitsa]", language = "russian", difficulty = "beginner"),
                    WordEntity(word = "рыба", translation = "fish", transcription = "[ryba]", language = "russian", difficulty = "beginner"),
                    WordEntity(word = "хлеб", translation = "bread", transcription = "[khleb]", language = "russian", difficulty = "beginner"),
                    WordEntity(word = "молоко", translation = "milk", transcription = "[moloko]", language = "russian", difficulty = "beginner"),
                    WordEntity(word = "сыр", translation = "cheese", transcription = "[syr]", language = "russian", difficulty = "beginner"),
                    WordEntity(word = "кофе", translation = "coffee", transcription = "[kofe]", language = "russian", difficulty = "beginner"),
                    WordEntity(word = "чай", translation = "tea", transcription = "[chay]", language = "russian", difficulty = "beginner"),
                    WordEntity(word = "город", translation = "city", transcription = "[gorod]", language = "russian", difficulty = "beginner"),
                    WordEntity(word = "страна", translation = "country", transcription = "[strana]", language = "russian", difficulty = "beginner"),
                    WordEntity(word = "река", translation = "river", transcription = "[reka]", language = "russian", difficulty = "beginner"),
                    WordEntity(word = "гора", translation = "mountain", transcription = "[gora]", language = "russian", difficulty = "beginner"),
                    WordEntity(word = "цветок", translation = "flower", transcription = "[tsvetok]", language = "russian", difficulty = "beginner"),
                    WordEntity(word = "дождь", translation = "rain", transcription = "[dozhd']", language = "russian", difficulty = "beginner"),
                    WordEntity(word = "снег", translation = "snow", transcription = "[sneg]", language = "russian", difficulty = "beginner"),
                    WordEntity(word = "ветер", translation = "wind", transcription = "[veter]", language = "russian", difficulty = "beginner"),
                    WordEntity(word = "счастливый", translation = "happy", transcription = "[schastlivyy]", language = "russian", difficulty = "beginner"),
                    WordEntity(word = "грустный", translation = "sad", transcription = "[grustnyy]", language = "russian", difficulty = "beginner"),
                    WordEntity(word = "большой", translation = "big", transcription = "[bol'shoy]", language = "russian", difficulty = "beginner"),
                    WordEntity(word = "маленький", translation = "small", transcription = "[malen'kiy]", language = "russian", difficulty = "beginner"),
                    WordEntity(word = "хороший", translation = "good", transcription = "[khoroshiy]", language = "russian", difficulty = "beginner"),
                    WordEntity(word = "плохой", translation = "bad", transcription = "[plokhoy]", language = "russian", difficulty = "beginner"),
                    WordEntity(word = "горячий", translation = "hot", transcription = "[goryachiy]", language = "russian", difficulty = "beginner"),
                    WordEntity(word = "холодный", translation = "cold", transcription = "[kholodnyy]", language = "russian", difficulty = "beginner"),
                    WordEntity(word = "новый", translation = "new", transcription = "[novyy]", language = "russian", difficulty = "beginner"),
                    WordEntity(word = "старый", translation = "old", transcription = "[staryy]", language = "russian", difficulty = "beginner"),
                    WordEntity(word = "день", translation = "day", transcription = "[den']", language = "russian", difficulty = "beginner"),
                    WordEntity(word = "ночь", translation = "night", transcription = "[noch']", language = "russian", difficulty = "beginner"),
                    WordEntity(word = "время", translation = "time", transcription = "[vremya]", language = "russian", difficulty = "beginner"),
                    WordEntity(word = "год", translation = "year", transcription = "[god]", language = "russian", difficulty = "beginner"),
                    WordEntity(word = "месяц", translation = "month", transcription = "[mesyats]", language = "russian", difficulty = "beginner"),
                    WordEntity(word = "неделя", translation = "week", transcription = "[nedelya]", language = "russian", difficulty = "beginner"),
                    WordEntity(word = "час", translation = "hour", transcription = "[chas]", language = "russian", difficulty = "beginner"),
                    WordEntity(word = "минута", translation = "minute", transcription = "[minuta]", language = "russian", difficulty = "beginner"),
                    WordEntity(word = "сейчас", translation = "now", transcription = "[seychas]", language = "russian", difficulty = "beginner"),
                    WordEntity(word = "тогда", translation = "then", transcription = "[togda]", language = "russian", difficulty = "beginner"),

                    // Русский - Intermediate (70 слов)
                    WordEntity(word = "компьютер", translation = "computer", transcription = "[komp'yuter]", language = "russian", difficulty = "intermediate"),
                    WordEntity(word = "данные", translation = "data", transcription = "[dannye]", language = "russian", difficulty = "intermediate"),
                    WordEntity(word = "интернет", translation = "internet", transcription = "[internet]", language = "russian", difficulty = "intermediate"),
                    WordEntity(word = "программное обеспечение", translation = "software", transcription = "[programmnoye obespecheniye]", language = "russian", difficulty = "intermediate"),
                    WordEntity(word = "аппаратное обеспечение", translation = "hardware", transcription = "[apparatnoye obespecheniye]", language = "russian", difficulty = "intermediate"),
                    WordEntity(word = "сеть", translation = "network", transcription = "[set']", language = "russian", difficulty = "intermediate"),
                    WordEntity(word = "база данных", translation = "database", transcription = "[baza dannykh]", language = "russian", difficulty = "intermediate"),
                    WordEntity(word = "сервер", translation = "server", transcription = "[server]", language = "russian", difficulty = "intermediate"),
                    WordEntity(word = "клиент", translation = "client", transcription = "[klient]", language = "russian", difficulty = "intermediate"),
                    WordEntity(word = "протокол", translation = "protocol", transcription = "[protokol]", language = "russian", difficulty = "intermediate"),
                    WordEntity(word = "браузер", translation = "browser", transcription = "[brauzer]", language = "russian", difficulty = "intermediate"),
                    WordEntity(word = "приложение", translation = "application", transcription = "[prilozheniye]", language = "russian", difficulty = "intermediate"),
                    WordEntity(word = "файл", translation = "file", transcription = "[fayl]", language = "russian", difficulty = "intermediate"),
                    WordEntity(word = "папка", translation = "folder", transcription = "[papka]", language = "russian", difficulty = "intermediate"),
                    WordEntity(word = "скачать", translation = "download", transcription = "[skachat']", language = "russian", difficulty = "intermediate"),
                    WordEntity(word = "загрузить", translation = "upload", transcription = "[zagruzit']", language = "russian", difficulty = "intermediate"),
                    WordEntity(word = "электронная почта", translation = "email", transcription = "[elektronnaya pochta]", language = "russian", difficulty = "intermediate"),
                    WordEntity(word = "пароль", translation = "password", transcription = "[parol']", language = "russian", difficulty = "intermediate"),
                    WordEntity(word = "имя пользователя", translation = "username", transcription = "[imya pol'zovatelya]", language = "russian", difficulty = "intermediate"),
                    WordEntity(word = "безопасность", translation = "security", transcription = "[bezopasnost']", language = "russian", difficulty = "intermediate"),
                    WordEntity(word = "офис", translation = "office", transcription = "[ofis]", language = "russian", difficulty = "intermediate"),
                    WordEntity(word = "встреча", translation = "meeting", transcription = "[vstrecha]", language = "russian", difficulty = "intermediate"),
                    WordEntity(word = "проект", translation = "project", transcription = "[proyekt]", language = "russian", difficulty = "intermediate"),
                    WordEntity(word = "команда", translation = "team", transcription = "[komanda]", language = "russian", difficulty = "intermediate"),
                    WordEntity(word = "работа", translation = "work", transcription = "[rabota]", language = "russian", difficulty = "intermediate"),
                    WordEntity(word = "работа", translation = "job", transcription = "[rabota]", language = "russian", difficulty = "intermediate"),
                    WordEntity(word = "босс", translation = "boss", transcription = "[boss]", language = "russian", difficulty = "intermediate"),
                    WordEntity(word = "коллега", translation = "colleague", transcription = "[kollega]", language = "russian", difficulty = "intermediate"),
                    WordEntity(word = "зарплата", translation = "salary", transcription = "[zarplata]", language = "russian", difficulty = "intermediate"),
                    WordEntity(word = "отпуск", translation = "vacation", transcription = "[otpusk]", language = "russian", difficulty = "intermediate"),
                    WordEntity(word = "путешествие", translation = "travel", transcription = "[puteshestviye]", language = "russian", difficulty = "intermediate"),
                    WordEntity(word = "отель", translation = "hotel", transcription = "[otel']", language = "russian", difficulty = "intermediate"),
                    WordEntity(word = "ресторан", translation = "restaurant", transcription = "[restoran]", language = "russian", difficulty = "intermediate"),
                    WordEntity(word = "меню", translation = "menu", transcription = "[menyu]", language = "russian", difficulty = "intermediate"),
                    WordEntity(word = "заказ", translation = "order", transcription = "[zakaz]", language = "russian", difficulty = "intermediate"),
                    WordEntity(word = "счёт", translation = "bill", transcription = "[schyot]", language = "russian", difficulty = "intermediate"),
                    WordEntity(word = "платить", translation = "pay", transcription = "[platit']", language = "russian", difficulty = "intermediate"),
                    WordEntity(word = "деньги", translation = "money", transcription = "[den'gi]", language = "russian", difficulty = "intermediate"),
                    WordEntity(word = "банк", translation = "bank", transcription = "[bank]", language = "russian", difficulty = "intermediate"),
                    WordEntity(word = "карта", translation = "card", transcription = "[karta]", language = "russian", difficulty = "intermediate"),
                    WordEntity(word = "телефон", translation = "phone", transcription = "[telefon]", language = "russian", difficulty = "intermediate"),
                    WordEntity(word = "звонить", translation = "call", transcription = "[zvonit']", language = "russian", difficulty = "intermediate"),
                    WordEntity(word = "сообщение", translation = "message", transcription = "[soobshcheniye]", language = "russian", difficulty = "intermediate"),
                    WordEntity(word = "читать", translation = "read", transcription = "[chitat']", language = "russian", difficulty = "intermediate"),
                    WordEntity(word = "писать", translation = "write", transcription = "[pisat']", language = "russian", difficulty = "intermediate"),
                    WordEntity(word = "говорить", translation = "speak", transcription = "[govorit']", language = "russian", difficulty = "intermediate"),
                    WordEntity(word = "слушать", translation = "listen", transcription = "[slushat']", language = "russian", difficulty = "intermediate"),
                    WordEntity(word = "музыка", translation = "music", transcription = "[muzyka]", language = "russian", difficulty = "intermediate"),
                    WordEntity(word = "фильм", translation = "movie", transcription = "[fil'm]", language = "russian", difficulty = "intermediate"),
                    WordEntity(word = "история", translation = "story", transcription = "[istoriya]", language = "russian", difficulty = "intermediate"),
                    WordEntity(word = "новости", translation = "news", transcription = "[novosti]", language = "russian", difficulty = "intermediate"),
                    WordEntity(word = "погода", translation = "weather", transcription = "[pogoda]", language = "russian", difficulty = "intermediate"),
                    WordEntity(word = "дождь", translation = "rain", transcription = "[dozhd']", language = "russian", difficulty = "intermediate"),
                    WordEntity(word = "солнечный", translation = "sunny", transcription = "[solnechnyy]", language = "russian", difficulty = "intermediate"),
                    WordEntity(word = "облачный", translation = "cloudy", transcription = "[oblachnyy]", language = "russian", difficulty = "intermediate"),
                    WordEntity(word = "спорт", translation = "sport", transcription = "[sport]", language = "russian", difficulty = "intermediate"),
                    WordEntity(word = "футбол", translation = "football", transcription = "[futbol]", language = "russian", difficulty = "intermediate"),
                    WordEntity(word = "баскетбол", translation = "basketball", transcription = "[basketbol]", language = "russian", difficulty = "intermediate"),
                    WordEntity(word = "бегать", translation = "run", transcription = "[begat']", language = "russian", difficulty = "intermediate"),
                    WordEntity(word = "плавать", translation = "swim", transcription = "[plavat']", language = "russian", difficulty = "intermediate"),
                    WordEntity(word = "здоровье", translation = "health", transcription = "[zdorov'ye]", language = "russian", difficulty = "intermediate"),
                    WordEntity(word = "доктор", translation = "doctor", transcription = "[doktor]", language = "russian", difficulty = "intermediate"),
                    WordEntity(word = "больница", translation = "hospital", transcription = "[bol'nitsa]", language = "russian", difficulty = "intermediate"),
                    WordEntity(word = "лекарство", translation = "medicine", transcription = "[lekarstvo]", language = "russian", difficulty = "intermediate"),
                    WordEntity(word = "помощь", translation = "help", transcription = "[pomoshch']", language = "russian", difficulty = "intermediate"),
                    WordEntity(word = "проблема", translation = "problem", transcription = "[problema]", language = "russian", difficulty = "intermediate"),
                    WordEntity(word = "решение", translation = "solution", transcription = "[resheniye]", language = "russian", difficulty = "intermediate"),
                    WordEntity(word = "идея", translation = "idea", transcription = "[ideya]", language = "russian", difficulty = "intermediate"),
                    WordEntity(word = "план", translation = "plan", transcription = "[plan]", language = "russian", difficulty = "intermediate"),

                    // Русский - Advanced (70 слов)
                    WordEntity(word = "алгоритм", translation = "algorithm", transcription = "[algoritm]", language = "russian", difficulty = "advanced"),
                    WordEntity(word = "шифрование", translation = "encryption", transcription = "[shifrovaniye]", language = "russian", difficulty = "advanced"),
                    WordEntity(word = "расшифровка", translation = "decryption", transcription = "[rasshifrovka]", language = "russian", difficulty = "advanced"),
                    WordEntity(word = "искусственный", translation = "artificial", transcription = "[iskusstvennyy]", language = "russian", difficulty = "advanced"),
                    WordEntity(word = "интеллект", translation = "intelligence", transcription = "[intellekt]", language = "russian", difficulty = "advanced"),
                    WordEntity(word = "машинное", translation = "machine", transcription = "[mashinnoye]", language = "russian", difficulty = "advanced"),
                    WordEntity(word = "обучение", translation = "learning", transcription = "[obucheniye]", language = "russian", difficulty = "advanced"),
                    WordEntity(word = "нейронная", translation = "neural", transcription = "[neyronnaya]", language = "russian", difficulty = "advanced"),
                    WordEntity(word = "сеть", translation = "network", transcription = "[set']", language = "russian", difficulty = "advanced"),
                    WordEntity(word = "квантовые", translation = "quantum", transcription = "[kvantovyye]", language = "russian", difficulty = "advanced"),
                    WordEntity(word = "вычисления", translation = "computing", transcription = "[vychisleniya]", language = "russian", difficulty = "advanced"),
                    WordEntity(word = "блокчейн", translation = "blockchain", transcription = "[blokcheyn]", language = "russian", difficulty = "advanced"),
                    WordEntity(word = "криптовалюта", translation = "cryptocurrency", transcription = "[kriptovalyuta]", language = "russian", difficulty = "advanced"),
                    WordEntity(word = "виртуальная", translation = "virtual", transcription = "[virtual'naya]", language = "russian", difficulty = "advanced"),
                    WordEntity(word = "реальность", translation = "reality", transcription = "[real'nost']", language = "russian", difficulty = "advanced"),
                    WordEntity(word = "расширенная", translation = "augmented", transcription = "[rasshirennaya]", language = "russian", difficulty = "advanced"),
                    WordEntity(word = "кибербезопасность", translation = "cybersecurity", transcription = "[kiberbezopasnost']", language = "russian", difficulty = "advanced"),
                    WordEntity(word = "большие данные", translation = "bigdata", transcription = "[bol'shiye dannye]", language = "russian", difficulty = "advanced"),
                    WordEntity(word = "облачные", translation = "cloud", transcription = "[oblachnyye]", language = "russian", difficulty = "advanced"),
                    WordEntity(word = "вычисления", translation = "computing", transcription = "[vychisleniya]", language = "russian", difficulty = "advanced"),
                    WordEntity(word = "философия", translation = "philosophy", transcription = "[filosofiya]", language = "russian", difficulty = "advanced"),
                    WordEntity(word = "экономика", translation = "economy", transcription = "[ekonomika]", language = "russian", difficulty = "advanced"),
                    WordEntity(word = "политика", translation = "politics", transcription = "[politika]", language = "russian", difficulty = "advanced"),
                    WordEntity(word = "общество", translation = "society", transcription = "[obshchestvo]", language = "russian", difficulty = "advanced"),
                    WordEntity(word = "культура", translation = "culture", transcription = "[kul'tura]", language = "russian", difficulty = "advanced"),
                    WordEntity(word = "история", translation = "history", transcription = "[istoriya]", language = "russian", difficulty = "advanced"),
                    WordEntity(word = "наука", translation = "science", transcription = "[nauka]", language = "russian", difficulty = "advanced"),
                    WordEntity(word = "технология", translation = "technology", transcription = "[tekhnologiya]", language = "russian", difficulty = "advanced"),
                    WordEntity(word = "окружающая среда", translation = "environment", transcription = "[okruzhayushchaya sreda]", language = "russian", difficulty = "advanced"),
                    WordEntity(word = "климат", translation = "climate", transcription = "[klimat]", language = "russian", difficulty = "advanced"),
                    WordEntity(word = "устойчивый", translation = "sustainable", transcription = "[ustoychivyy]", language = "russian", difficulty = "advanced"),
                    WordEntity(word = "инновация", translation = "innovation", transcription = "[innovatsiya]", language = "russian", difficulty = "advanced"),
                    WordEntity(word = "исследование", translation = "research", transcription = "[issledovaniye]", language = "russian", difficulty = "advanced"),
                    WordEntity(word = "теория", translation = "theory", transcription = "[teoriya]", language = "russian", difficulty = "advanced"),
                    WordEntity(word = "гипотеза", translation = "hypothesis", transcription = "[gipoteza]", language = "russian", difficulty = "advanced"),
                    WordEntity(word = "эксперимент", translation = "experiment", transcription = "[eksperiment]", language = "russian", difficulty = "advanced"),
                    WordEntity(word = "анализ", translation = "analysis", transcription = "[analiz]", language = "russian", difficulty = "advanced"),
                    WordEntity(word = "заключение", translation = "conclusion", transcription = "[zaklyucheniye]", language = "russian", difficulty = "advanced"),
                    WordEntity(word = "дебаты", translation = "debate", transcription = "[debaty]", language = "russian", difficulty = "advanced"),
                    WordEntity(word = "аргумент", translation = "argument", transcription = "[argument]", language = "russian", difficulty = "advanced"),
                    WordEntity(word = "перспектива", translation = "perspective", transcription = "[perspektiva]", language = "russian", difficulty = "advanced"),
                    WordEntity(word = "этика", translation = "ethics", transcription = "[etika]", language = "russian", difficulty = "advanced"),
                    WordEntity(word = "мораль", translation = "morality", transcription = "[moral']", language = "russian", difficulty = "advanced"),
                    WordEntity(word = "справедливость", translation = "justice", transcription = "[spravedlivost']", language = "russian", difficulty = "advanced"),
                    WordEntity(word = "права", translation = "rights", transcription = "[prava]", language = "russian", difficulty = "advanced"),
                    WordEntity(word = "свобода", translation = "freedom", transcription = "[svoboda]", language = "russian", difficulty = "advanced"),
                    WordEntity(word = "демократия", translation = "democracy", transcription = "[demokratiya]", language = "russian", difficulty = "advanced"),
                    WordEntity(word = "капитализм", translation = "capitalism", transcription = "[kapitalizm]", language = "russian", difficulty = "advanced"),
                    WordEntity(word = "социализм", translation = "socialism", transcription = "[sotsializm]", language = "russian", difficulty = "advanced"),
                    WordEntity(word = "глобализация", translation = "globalization", transcription = "[globalizatsiya]", language = "russian", difficulty = "advanced"),
                    WordEntity(word = "торговля", translation = "trade", transcription = "[torgovlya]", language = "russian", difficulty = "advanced"),
                    WordEntity(word = "рынок", translation = "market", transcription = "[rynok]", language = "russian", difficulty = "advanced"),
                    WordEntity(word = "инвестиция", translation = "investment", transcription = "[investitsiya]", language = "russian", difficulty = "advanced"),
                    WordEntity(word = "прибыль", translation = "profit", transcription = "[pribyl']", language = "russian", difficulty = "advanced"),
                    WordEntity(word = "убыток", translation = "loss", transcription = "[ubytok]", language = "russian", difficulty = "advanced"),
                    WordEntity(word = "стратегия", translation = "strategy", transcription = "[strategiya]", language = "russian", difficulty = "advanced"),
                    WordEntity(word = "лидерство", translation = "leadership", transcription = "[liderstvo]", language = "russian", difficulty = "advanced"),
                    WordEntity(word = "управление", translation = "management", transcription = "[upravleniye]", language = "russian", difficulty = "advanced"),
                    WordEntity(word = "инновация", translation = "innovation", transcription = "[innovatsiya]", language = "russian", difficulty = "advanced"),
                    WordEntity(word = "креативность", translation = "creativity", transcription = "[kreativnost']", language = "russian", difficulty = "advanced"),
                    WordEntity(word = "психология", translation = "psychology", transcription = "[psikhologiya]", language = "russian", difficulty = "advanced"),
                    WordEntity(word = "поведение", translation = "behavior", transcription = "[povedeniye]", language = "russian", difficulty = "advanced"),
                    WordEntity(word = "эмоция", translation = "emotion", transcription = "[emotsiya]", language = "russian", difficulty = "advanced"),
                    WordEntity(word = "мотивация", translation = "motivation", transcription = "[motivatsiya]", language = "russian", difficulty = "advanced"),
                    WordEntity(word = "стресс", translation = "stress", transcription = "[stress]", language = "russian", difficulty = "advanced"),
                    WordEntity(word = "здоровье", translation = "health", transcription = "[zdorov'ye]", language = "russian", difficulty = "advanced"),
                    WordEntity(word = "медицина", translation = "medicine", transcription = "[meditsina]", language = "russian", difficulty = "advanced"),
                    WordEntity(word = "биология", translation = "biology", transcription = "[biologiya]", language = "russian", difficulty = "advanced"),
                    WordEntity(word = "физика", translation = "physics", transcription = "[fizika]", language = "russian", difficulty = "advanced"),
                    WordEntity(word = "химия", translation = "chemistry", transcription = "[khimiya]", language = "russian", difficulty = "advanced"),

                    // Испанский - Beginner (70 слов)
                    WordEntity(word = "hola", translation = "привет", transcription = "[ˈola]", language = "spanish", difficulty = "beginner"),
                    WordEntity(word = "mundo", translation = "мир", transcription = "[ˈmundo]", language = "spanish", difficulty = "beginner"),
                    WordEntity(word = "manzana", translation = "яблоко", transcription = "[manˈθana]", language = "spanish", difficulty = "beginner"),
                    WordEntity(word = "libro", translation = "книга", transcription = "[ˈliβɾo]", language = "spanish", difficulty = "beginner"),
                    WordEntity(word = "gato", translation = "кошка", transcription = "[ˈɡato]", language = "spanish", difficulty = "beginner"),
                    WordEntity(word = "perro", translation = "собака", transcription = "[ˈpero]", language = "spanish", difficulty = "beginner"),
                    WordEntity(word = "casa", translation = "дом", transcription = "[ˈkasa]", language = "spanish", difficulty = "beginner"),
                    WordEntity(word = "árbol", translation = "дерево", transcription = "[ˈaɾβol]", language = "spanish", difficulty = "beginner"),
                    WordEntity(word = "coche", translation = "машина", transcription = "[ˈkotʃe]",language = "spanish", difficulty = "beginner"),
                    WordEntity(word = "sol", translation = "солнце", transcription = "[sol]", language = "spanish", difficulty = "beginner"),
                    WordEntity(word = "luna", translation = "луна", transcription = "[ˈluna]", language = "spanish", difficulty = "beginner"),
                    WordEntity(word = "agua", translation = "вода", transcription = "[ˈaɡwa]", language = "spanish", difficulty = "beginner"),
                    WordEntity(word = "comida", translation = "еда", transcription = "[koˈmiða]", language = "spanish", difficulty = "beginner"),
                    WordEntity(word = "amigo", translation = "друг", transcription = "[aˈmiɡo]", language = "spanish", difficulty = "beginner"),
                    WordEntity(word = "familia", translation = "семья", transcription = "[faˈmilja]", language = "spanish", difficulty = "beginner"),
                    WordEntity(word = "escuela", translation = "школа", transcription = "[esˈkwela]", language = "spanish", difficulty = "beginner"),
                    WordEntity(word = "profesor", translation = "учитель", transcription = "[pɾofeˈsoɾ]", language = "spanish", difficulty = "beginner"),
                    WordEntity(word = "estudiante", translation = "ученик", transcription = "[estuˈðjante]", language = "spanish", difficulty = "beginner"),
                    WordEntity(word = "bolígrafo", translation = "ручка", transcription = "[boˈliɡɾafo]", language = "spanish", difficulty = "beginner"),
                    WordEntity(word = "papel", translation = "бумага", transcription = "[paˈpel]", language = "spanish", difficulty = "beginner"),
                    WordEntity(word = "si", translation = "да", transcription = "[si]", language = "spanish", difficulty = "beginner"),
                    WordEntity(word = "no", translation = "нет", transcription = "[no]", language = "spanish", difficulty = "beginner"),
                    WordEntity(word = "por favor", translation = "пожалуйста", transcription = "[poɾ faˈβoɾ]", language = "spanish", difficulty = "beginner"),
                    WordEntity(word = "gracias", translation = "спасибо", transcription = "[ˈɡɾaθjas]", language = "spanish", difficulty = "beginner"),
                    WordEntity(word = "lo siento", translation = "извините", transcription = "[lo ˈsjɛnto]", language = "spanish", difficulty = "beginner"),
                    WordEntity(word = "madre", translation = "мама", transcription = "[ˈmaðɾe]", language = "spanish", difficulty = "beginner"),
                    WordEntity(word = "padre", translation = "папа", transcription = "[ˈpaðɾe]", language = "spanish", difficulty = "beginner"),
                    WordEntity(word = "hermano", translation = "брат", transcription = "[eɾˈmano]", language = "spanish", difficulty = "beginner"),
                    WordEntity(word = "hermana", translation = "сестра", transcription = "[eɾˈmana]", language = "spanish", difficulty = "beginner"),
                    WordEntity(word = "niño", translation = "ребёнок", transcription = "[ˈniɲo]", language = "spanish", difficulty = "beginner"),
                    WordEntity(word = "uno", translation = "один", transcription = "[ˈuno]", language = "spanish", difficulty = "beginner"),
                    WordEntity(word = "dos", translation = "два", transcription = "[dos]", language = "spanish", difficulty = "beginner"),
                    WordEntity(word = "tres", translation = "три", transcription = "[tɾes]", language = "spanish", difficulty = "beginner"),
                    WordEntity(word = "rojo", translation = "красный", transcription = "[ˈroxo]", language = "spanish", difficulty = "beginner"),
                    WordEntity(word = "azul", translation = "синий", transcription = "[aˈθul]", language = "spanish", difficulty = "beginner"),
                    WordEntity(word = "verde", translation = "зелёный", transcription = "[ˈbeɾðe]", language = "spanish", difficulty = "beginner"),
                    WordEntity(word = "pájaro", translation = "птица", transcription = "[ˈpaxaɾo]", language = "spanish", difficulty = "beginner"),
                    WordEntity(word = "pez", translation = "рыба", transcription = "[peθ]", language = "spanish", difficulty = "beginner"),
                    WordEntity(word = "pan", translation = "хлеб", transcription = "[pan]", language = "spanish", difficulty = "beginner"),
                    WordEntity(word = "leche", translation = "молоко", transcription = "[ˈletʃe]", language = "spanish", difficulty = "beginner"),
                    WordEntity(word = "queso", translation = "сыр", transcription = "[ˈkeso]", language = "spanish", difficulty = "beginner"),
                    WordEntity(word = "café", translation = "кофе", transcription = "[kaˈfe]", language = "spanish", difficulty = "beginner"),
                    WordEntity(word = "té", translation = "чай", transcription = "[te]", language = "spanish", difficulty = "beginner"),
                    WordEntity(word = "ciudad", translation = "город", transcription = "[θjuˈðað]", language = "spanish", difficulty = "beginner"),
                    WordEntity(word = "país", translation = "страна", transcription = "[paˈis]", language = "spanish", difficulty = "beginner"),
                    WordEntity(word = "río", translation = "река", transcription = "[ˈrio]", language = "spanish", difficulty = "beginner"),
                    WordEntity(word = "montaña", translation = "гора", transcription = "[monˈtaɲa]", language = "spanish", difficulty = "beginner"),
                    WordEntity(word = "flor", translation = "цветок", transcription = "[floɾ]", language = "spanish", difficulty = "beginner"),
                    WordEntity(word = "lluvia", translation = "дождь", transcription = "[ˈʎuβja]", language = "spanish", difficulty = "beginner"),
                    WordEntity(word = "nieve", translation = "снег", transcription = "[ˈnjeβe]", language = "spanish", difficulty = "beginner"),
                    WordEntity(word = "viento", translation = "ветер", transcription = "[ˈbjento]", language = "spanish", difficulty = "beginner"),
                    WordEntity(word = "feliz", translation = "счастливый", transcription = "[feˈliθ]", language = "spanish", difficulty = "beginner"),
                    WordEntity(word = "triste", translation = "грустный", transcription = "[ˈtɾiste]", language = "spanish", difficulty = "beginner"),
                    WordEntity(word = "grande", translation = "большой", transcription = "[ˈɡɾande]", language = "spanish", difficulty = "beginner"),
                    WordEntity(word = "pequeño", translation = "маленький", transcription = "[peˈkeɲo]", language = "spanish", difficulty = "beginner"),
                    WordEntity(word = "bueno", translation = "хороший", transcription = "[ˈbweno]", language = "spanish", difficulty = "beginner"),
                    WordEntity(word = "malo", translation = "плохой", transcription = "[ˈmalo]", language = "spanish", difficulty = "beginner"),
                    WordEntity(word = "caliente", translation = "горячий", transcription = "[kaˈljente]", language = "spanish", difficulty = "beginner"),
                    WordEntity(word = "frío", translation = "холодный", transcription = "[ˈfɾio]", language = "spanish", difficulty = "beginner"),
                    WordEntity(word = "nuevo", translation = "новый", transcription = "[ˈnweβo]", language = "spanish", difficulty = "beginner"),
                    WordEntity(word = "viejo", translation = "старый", transcription = "[ˈbjeho]", language = "spanish", difficulty = "beginner"),
                    WordEntity(word = "día", translation = "день", transcription = "[ˈdia]", language = "spanish", difficulty = "beginner"),
                    WordEntity(word = "noche", translation = "ночь", transcription = "[ˈnotʃe]", language = "spanish", difficulty = "beginner"),
                    WordEntity(word = "tiempo", translation = "время", transcription = "[ˈtjempo]", language = "spanish", difficulty = "beginner"),
                    WordEntity(word = "año", translation = "год", transcription = "[ˈaɲo]", language = "spanish", difficulty = "beginner"),
                    WordEntity(word = "mes", translation = "месяц", transcription = "[mes]", language = "spanish", difficulty = "beginner"),
                    WordEntity(word = "semana", translation = "неделя", transcription = "[seˈmana]", language = "spanish", difficulty = "beginner"),
                    WordEntity(word = "hora", translation = "час", transcription = "[ˈoɾa]", language = "spanish", difficulty = "beginner"),
                    WordEntity(word = "minuto", translation = "минута", transcription = "[miˈnuto]", language = "spanish", difficulty = "beginner"),
                    WordEntity(word = "ahora", translation = "сейчас", transcription = "[aˈoɾa]", language = "spanish", difficulty = "beginner"),
                    WordEntity(word = "entonces", translation = "тогда", transcription = "[enˈtonθes]", language = "spanish", difficulty = "beginner"),

                    // Испанский - Intermediate (70 слов)
                    WordEntity(word = "computadora", translation = "компьютер", transcription = "[kompuˈtaðoɾa]", language = "spanish", difficulty = "intermediate"),
                    WordEntity(word = "datos", translation = "данные", transcription = "[ˈdatos]", language = "spanish", difficulty = "intermediate"),
                    WordEntity(word = "internet", translation = "интернет", transcription = "[inteɾˈnet]", language = "spanish", difficulty = "intermediate"),
                    WordEntity(word = "software", translation = "программное обеспечение", transcription = "[ˈsoftwaɾe]", language = "spanish", difficulty = "intermediate"),
                    WordEntity(word = "hardware", translation = "аппаратное обеспечение", transcription = "[ˈaɾdwaɾe]", language = "spanish", difficulty = "intermediate"),
                    WordEntity(word = "red", translation = "сеть", transcription = "[ɾeð]", language = "spanish", difficulty = "intermediate"),
                    WordEntity(word = "base de datos", translation = "база данных", transcription = "[ˈbase ðe ˈdatos]", language = "spanish", difficulty = "intermediate"),
                    WordEntity(word = "servidor", translation = "сервер", transcription = "[seɾβiˈðoɾ]", language = "spanish", difficulty = "intermediate"),
                    WordEntity(word = "cliente", translation = "клиент", transcription = "[ˈkljente]", language = "spanish", difficulty = "intermediate"),
                    WordEntity(word = "protocolo", translation = "протокол", transcription = "[pɾotoˈkolo]", language = "spanish", difficulty = "intermediate"),
                    WordEntity(word = "navegador", translation = "браузер", transcription = "[naβeɡaˈðoɾ]", language = "spanish", difficulty = "intermediate"),
                    WordEntity(word = "aplicación", translation = "приложение", transcription = "[apliˈkaθjon]", language = "spanish", difficulty = "intermediate"),
                    WordEntity(word = "archivo", translation = "файл", transcription = "[aɾˈtʃiβo]", language = "spanish", difficulty = "intermediate"),
                    WordEntity(word = "carpeta", translation = "папка", transcription = "[kaɾˈpeta]", language = "spanish", difficulty = "intermediate"),
                    WordEntity(word = "descargar", translation = "скачать", transcription = "[deskaɾˈɡaɾ]", language = "spanish", difficulty = "intermediate"),
                    WordEntity(word = "subir", translation = "загрузить", transcription = "[suˈβiɾ]", language = "spanish", difficulty = "intermediate"),
                    WordEntity(word = "correo electrónico", translation = "электронная почта", transcription = "[koˈreo eleˈktɾoniko]", language = "spanish", difficulty = "intermediate"),
                    WordEntity(word = "contraseña", translation = "пароль", transcription = "[kontɾaˈseɲa]", language = "spanish", difficulty = "intermediate"),
                    WordEntity(word = "nombre de usuario", translation = "имя пользователя", transcription = "[ˈnombɾe ðe usuˈaɾjo]", language = "spanish", difficulty = "intermediate"),
                    WordEntity(word = "seguridad", translation = "безопасность", transcription = "[seɡuɾiˈðað]", language = "spanish", difficulty = "intermediate"),
                    WordEntity(word = "oficina", translation = "офис", transcription = "[oˈfiθina]", language = "spanish", difficulty = "intermediate"),
                    WordEntity(word = "reunión", translation = "встреча", transcription = "[reuˈnjon]", language = "spanish", difficulty = "intermediate"),
                    WordEntity(word = "proyecto", translation = "проект", transcription = "[pɾoˈʝekto]", language = "spanish", difficulty = "intermediate"),
                    WordEntity(word = "equipo", translation = "команда", transcription = "[eˈkipo]", language = "spanish", difficulty = "intermediate"),
                    WordEntity(word = "trabajo", translation = "работа", transcription = "[tɾaˈβaxo]", language = "spanish", difficulty = "intermediate"),
                    WordEntity(word = "jefe", translation = "босс", transcription = "[ˈxefe]", language = "spanish", difficulty = "intermediate"),
                    WordEntity(word = "colega", translation = "коллега", transcription = "[koˈleɡa]", language = "spanish", difficulty = "intermediate"),
                    WordEntity(word = "salario", translation = "зарплата", transcription = "[saˈlaɾjo]", language = "spanish", difficulty = "intermediate"),
                    WordEntity(word = "vacaciones", translation = "отпуск", transcription = "[bakaˈθjones]", language = "spanish", difficulty = "intermediate"),
                    WordEntity(word = "viaje", translation = "путешествие", transcription = "[ˈbjaxe]", language = "spanish", difficulty = "intermediate"),
                    WordEntity(word = "hotel", translation = "отель", transcription = "[oˈtel]", language = "spanish", difficulty = "intermediate"),
                    WordEntity(word = "restaurante", translation = "ресторан", transcription = "[ɾestaʊˈɾante]", language = "spanish", difficulty = "intermediate"),
                    WordEntity(word = "menú", translation = "меню", transcription = "[meˈnu]", language = "spanish", difficulty = "intermediate"),
                    WordEntity(word = "pedido", translation = "заказ", transcription = "[peˈðiðo]", language = "spanish", difficulty = "intermediate"),
                    WordEntity(word = "cuenta", translation = "счёт", transcription = "[ˈkwenta]", language = "spanish", difficulty = "intermediate"),
                    WordEntity(word = "pagar", translation = "платить", transcription = "[paˈɡaɾ]", language = "spanish", difficulty = "intermediate"),
                    WordEntity(word = "dinero", translation = "деньги", transcription = "[diˈneɾo]", language = "spanish", difficulty = "intermediate"),
                    WordEntity(word = "banco", translation = "банк", transcription = "[ˈbaŋko]", language = "spanish", difficulty = "intermediate"),
                    WordEntity(word = "tarjeta", translation = "карта", transcription = "[taɾˈxeta]", language = "spanish", difficulty = "intermediate"),
                    WordEntity(word = "teléfono", translation = "телефон", transcription = "[teˈlefono]", language = "spanish", difficulty = "intermediate"),
                    WordEntity(word = "llamar", translation = "звонить", transcription = "[ʎaˈmaɾ]", language = "spanish", difficulty = "intermediate"),
                    WordEntity(word = "mensaje", translation = "сообщение", transcription = "[menˈsaxe]", language = "spanish", difficulty = "intermediate"),
                    WordEntity(word = "leer", translation = "читать", transcription = "[leˈeɾ]", language = "spanish", difficulty = "intermediate"),
                    WordEntity(word = "escribir", translation = "писать", transcription = "[eskɾiˈβiɾ]", language = "spanish", difficulty = "intermediate"),
                    WordEntity(word = "hablar", translation = "говорить", transcription = "[aˈβlaɾ]", language = "spanish", difficulty = "intermediate"),
                    WordEntity(word = "escuchar", translation = "слушать", transcription = "[eskuˈtʃaɾ]", language = "spanish", difficulty = "intermediate"),
                    WordEntity(word = "música", translation = "музыка", transcription = "[ˈmusika]", language = "spanish", difficulty = "intermediate"),
                    WordEntity(word = "película", translation = "фильм", transcription = "[peˈlikula]", language = "spanish", difficulty = "intermediate"),
                    WordEntity(word = "historia", translation = "история", transcription = "[isˈtoɾja]", language = "spanish", difficulty = "intermediate"),
                    WordEntity(word = "noticias", translation = "новости", transcription = "[noˈtiθjas]", language = "spanish", difficulty = "intermediate"),
                    WordEntity(word = "tiempo", translation = "погода", transcription = "[ˈtjempo]", language = "spanish", difficulty = "intermediate"),
                    WordEntity(word = "lluvia", translation = "дождь", transcription = "[ˈʎuβja]", language = "spanish", difficulty = "intermediate"),
                    WordEntity(word = "soleado", translation = "солнечный", transcription = "[soˈleaðo]", language = "spanish", difficulty = "intermediate"),
                    WordEntity(word = "nublado", translation = "облачный", transcription = "[nuˈβlaðo]", language = "spanish", difficulty = "intermediate"),
                    WordEntity(word = "deporte", translation = "спорт", transcription = "[deˈpoɾte]", language = "spanish", difficulty = "intermediate"),
                    WordEntity(word = "fútbol", translation = "футбол", transcription = "[ˈfutβol]", language = "spanish", difficulty = "intermediate"),
                    WordEntity(word = "baloncesto", translation = "баскетбол", transcription = "[balonˈθesto]", language = "spanish", difficulty = "intermediate"),
                    WordEntity(word = "correr", translation = "бегать", transcription = "[koˈreɾ]", language = "spanish", difficulty = "intermediate"),
                    WordEntity(word = "nadar", translation = "плавать", transcription = "[naˈðaɾ]", language = "spanish", difficulty = "intermediate"),
                    WordEntity(word = "salud", translation = "здоровье", transcription = "[saˈluð]", language = "spanish", difficulty = "intermediate"),
                    WordEntity(word = "doctor", translation = "доктор", transcription = "[ˈdoktoɾ]", language = "spanish", difficulty = "intermediate"),
                    WordEntity(word = "hospital", translation = "больница", transcription = "[ospiˈtal]", language = "spanish", difficulty = "intermediate"),
                    WordEntity(word = "medicina", translation = "лекарство", transcription = "[meðiˈθina]", language = "spanish", difficulty = "intermediate"),
                    WordEntity(word = "ayuda", translation = "помощь", transcription = "[aˈʝuða]", language = "spanish", difficulty = "intermediate"),
                    WordEntity(word = "problema", translation = "проблема", transcription = "[pɾoˈβlema]", language = "spanish", difficulty = "intermediate"),
                    WordEntity(word = "solución", translation = "решение", transcription = "[soluˈθjon]", language = "spanish", difficulty = "intermediate"),
                    WordEntity(word = "idea", translation = "идея", transcription = "[iˈðea]", language = "spanish", difficulty = "intermediate"),
                    WordEntity(word = "plan", translation = "план", transcription = "[plan]", language = "spanish", difficulty = "intermediate"),

                    // Испанский - Advanced (70 слов)
                    WordEntity(word = "algoritmo", translation = "алгоритм", transcription = "[alɡoˈɾitmo]", language = "spanish", difficulty = "advanced"),
                    WordEntity(word = "cifrado", translation = "шифрование", transcription = "[θifˈɾaðo]", language = "spanish", difficulty = "advanced"),
                    WordEntity(word = "descifrado", translation = "расшифровка", transcription = "[desθifˈɾaðo]", language = "spanish", difficulty = "advanced"),
                    WordEntity(word = "artificial", translation = "искусственный", transcription = "[aɾtifiˈθjal]", language = "spanish", difficulty = "advanced"),
                    WordEntity(word = "inteligencia", translation = "интеллект", transcription = "[inteliˈxensja]", language = "spanish", difficulty = "advanced"),
                    WordEntity(word = "máquina", translation = "машина", transcription = "[ˈmakina]", language = "spanish", difficulty = "advanced"),
                    WordEntity(word = "aprendizaje", translation = "обучение", transcription = "[apɾendiˈθaxe]", language = "spanish", difficulty = "advanced"),
                    WordEntity(word = "neuronal", translation = "нейронный", transcription = "[neuˈɾonal]", language = "spanish", difficulty = "advanced"),
                    WordEntity(word = "red", translation = "сеть", transcription = "[ɾeð]", language = "spanish", difficulty = "advanced"),
                    WordEntity(word = "cuántico", translation = "квантовый", transcription = "[ˈkwantiko]", language = "spanish", difficulty = "advanced"),
                    WordEntity(word = "computación", translation = "вычисления", transcription = "[komputaˈθjon]", language = "spanish", difficulty = "advanced"),
                    WordEntity(word = "blockchain", translation = "блокчейн", transcription = "[blokˈtʃein]", language = "spanish", difficulty = "advanced"),
                    WordEntity(word = "criptomoneda", translation = "криптовалюта", transcription = "[kɾiptomoˈneða]", language = "spanish", difficulty = "advanced"),
                    WordEntity(word = "virtual", translation = "виртуальный", transcription = "[biɾˈtwal]", language = "spanish", difficulty = "advanced"),
                    WordEntity(word = "realidad", translation = "реальность", transcription = "[reaˈliðað]", language = "spanish", difficulty = "advanced"),
                    WordEntity(word = "aumentada", translation = "расширенный", transcription = "[aumenˈtaða]", language = "spanish", difficulty = "advanced"),
                    WordEntity(word = "ciberseguridad", translation = "кибербезопасность", transcription = "[θiβeɾseɡuɾiˈðað]", language = "spanish", difficulty = "advanced"),
                    WordEntity(word = "big data", translation = "большие данные", transcription = "[biɡ ˈdata]", language = "spanish", difficulty = "advanced"),
                    WordEntity(word = "nube", translation = "облако", transcription = "[ˈnuβe]", language = "spanish", difficulty = "advanced"),
                    WordEntity(word = "computación", translation = "вычисления", transcription = "[komputaˈθjon]", language = "spanish", difficulty = "advanced"),
                    WordEntity(word = "filosofía", translation = "философия", transcription = "[filo soˈfi a]", language = "spanish", difficulty = "advanced"),
                    WordEntity(word = "economía", translation = "экономика", transcription = "[eko noˈmi a]", language = "spanish", difficulty = "advanced"),
                    WordEntity(word = "política", translation = "политика", transcription = "[poˈlitika]", language = "spanish", difficulty = "advanced"),
                    WordEntity(word = "sociedad", translation = "общество", transcription = "[soθjeˈðað]", language = "spanish", difficulty = "advanced"),
                    WordEntity(word = "cultura", translation = "культура", transcription = "[kulˈtuɾa]", language = "spanish", difficulty = "advanced"),
                    WordEntity(word = "historia", translation = "история", transcription = "[isˈtoɾja]", language = "spanish", difficulty = "advanced"),
                    WordEntity(word = "ciencia", translation = "наука", transcription = "[ˈθjenθja]", language = "spanish", difficulty = "advanced"),
                    WordEntity(word = "tecnología", translation = "технология", transcription = "[tekno loˈxi a]", language = "spanish", difficulty = "advanced"),
                    WordEntity(word = "medio ambiente", translation = "окружающая среда", transcription = "[ˈmeðjo amˈbjente]", language = "spanish", difficulty = "advanced"),
                    WordEntity(word = "clima", translation = "климат", transcription = "[ˈklima]", language = "spanish", difficulty = "advanced"),
                    WordEntity(word = "sostenible", translation = "устойчивый", transcription = "[sosteˈniβle]", language = "spanish", difficulty = "advanced"),
                    WordEntity(word = "innovación", translation = "инновация", transcription = "[innoβaˈθjon]", language = "spanish", difficulty = "advanced"),
                    WordEntity(word = "investigación", translation = "исследование", transcription = "[inβestiɡaˈθjon]", language = "spanish", difficulty = "advanced"),
                    WordEntity(word = "teoría", translation = "теория", transcription = "[te oˈɾi a]", language = "spanish", difficulty = "advanced"),
                    WordEntity(word = "hipótesis", translation = "гипотеза", transcription = "[iˈpotesis]", language = "spanish", difficulty = "advanced"),
                    WordEntity(word = "experimento", translation = "эксперимент", transcription = "[ekspeɾiˈmento]", language = "spanish", difficulty = "advanced"),
                    WordEntity(word = "análisis", translation = "анализ", transcription = "[aˈnalisis]", language = "spanish", difficulty = "advanced"),
                    WordEntity(word = "conclusión", translation = "заключение", transcription = "[konkluˈsjon]", language = "spanish", difficulty = "advanced"),
                    WordEntity(word = "debate", translation = "дебаты", transcription = "[deˈβate]", language = "spanish", difficulty = "advanced"),
                    WordEntity(word = "argumento", translation = "аргумент", transcription = "[aɾɡuˈmento]", language = "spanish", difficulty = "advanced"),
                    WordEntity(word = "perspectiva", translation = "перспектива", transcription = "[peɾspekˈtiβa]", language = "spanish", difficulty = "advanced"),
                    WordEntity(word = "ética", translation = "этика", transcription = "[ˈetika]", language = "spanish", difficulty = "advanced"),
                    WordEntity(word = "moral", translation = "мораль", transcription = "[moˈɾal]", language = "spanish", difficulty = "advanced"),
                    WordEntity(word = "justicia", translation = "справедливость", transcription = "[xusˈtiθja]", language = "spanish", difficulty = "advanced"),
                    WordEntity(word = "derechos", translation = "права", transcription = "[deˈɾetʃos]", language = "spanish", difficulty = "advanced"),
                    WordEntity(word = "libertad", translation = "свобода", transcription = "[liβeɾˈtað]", language = "spanish", difficulty = "advanced"),
                    WordEntity(word = "democracia", translation = "демократия", transcription = "[demoˈkɾaθja]", language = "spanish", difficulty = "advanced"),
                    WordEntity(word = "capitalismo", translation = "капитализм", transcription = "[kapitaˈlismo]", language = "spanish", difficulty = "advanced"),
                    WordEntity(word = "socialismo", translation = "социализм", transcription = "[soθjaˈlismo]", language = "spanish", difficulty = "advanced"),
                    WordEntity(word = "globalización", translation = "глобализация", transcription = "[ɡloβalisaˈθjon]", language = "spanish", difficulty = "advanced"),
                    WordEntity(word = "comercio", translation = "торговля", transcription = "[koˈmeɾθjo]", language = "spanish", difficulty = "advanced"),
                    WordEntity(word = "mercado", translation = "рынок", transcription = "[meɾˈkaðo]", language = "spanish", difficulty = "advanced"),
                    WordEntity(word = "inversión", translation = "инвестиция", transcription = "[inbeɾˈsjon]", language = "spanish", difficulty = "advanced"),
                    WordEntity(word = "beneficio", translation = "прибыль", transcription = "[beneˈfiθjo]", language = "spanish", difficulty = "advanced"),
                    WordEntity(word = "pérdida", translation = "убыток", transcription = "[ˈpeɾðiða]", language = "spanish", difficulty = "advanced"),
                    WordEntity(word = "estrategia", translation = "стратегия", transcription = "[estɾaˈtexja]", language = "spanish", difficulty = "advanced"),
                    WordEntity(word = "liderazgo", translation = "лидерство", transcription = "[liðeˈɾasɡo]", language = "spanish", difficulty = "advanced"),
                    WordEntity(word = "gestión", translation = "управление", transcription = "[xesˈtjon]", language = "spanish", difficulty = "advanced"),
                    WordEntity(word = "innovación", translation = "инновация", transcription = "[innoβaˈθjon]", language = "spanish", difficulty = "advanced"),
                    WordEntity(word = "creatividad", translation = "креативность", transcription = "[kɾeatiβiˈðað]", language = "spanish", difficulty = "advanced"),
                    WordEntity(word = "psicología", translation = "психология", transcription = "[psiko loˈxi a]", language = "spanish", difficulty = "advanced"),
                    WordEntity(word = "comportamiento", translation = "поведение", transcription = "[kompoɾtaˈmjento]", language = "spanish", difficulty = "advanced"),
                    WordEntity(word = "emoción", translation = "эмоция", transcription = "[emoˈθjon]", language = "spanish", difficulty = "advanced"),
                    WordEntity(word = "motivación", translation = "мотивация", transcription = "[motiβaˈθjon]", language = "spanish", difficulty = "advanced"),
                    WordEntity(word = "estrés", translation = "стресс", transcription = "[esˈtɾes]", language = "spanish", difficulty = "advanced"),
                    WordEntity(word = "salud", translation = "здоровье", transcription = "[saˈluð]", language = "spanish", difficulty = "advanced"),
                    WordEntity(word = "medicina", translation = "медицина", transcription = "[meðiˈθina]", language = "spanish", difficulty = "advanced"),
                    WordEntity(word = "biología", translation = "биология", transcription = "[bjo loˈxi a]", language = "spanish", difficulty = "advanced"),
                    WordEntity(word = "física", translation = "физика", transcription = "[ˈfisi ka]", language = "spanish", difficulty = "advanced"),
                    WordEntity(word = "química", translation = "химия", transcription = "[ˈkimika]", language = "spanish", difficulty = "advanced")
                ))
            }
        }
    }
}